= Notes

== Install metrics-server

 helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/


 helm upgrade --install metrics-server metrics-server/metrics-server


== preinstalation Prometeuse

 kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml

== Deploy

 helm upgrade --install  my-ph-ee-g2psandbox ./g2p-sandbox/  --create-namespace --namespace paymenthub

=== Delete

  helm delete my-ph-ee-g2psandbox -n paymenthub

 kubectl delete namespace paymenthub



set `SECURITY_JWS_ENABLE: false` into *ph-ee-connector-common* pod


== Examples of requests

https://mifos.gitbook.io/docs/payment-hub-ee/overview/bulk-disbursement-integration#id-1.-bulk-transfer

== logs

kubectl logs -n paymenthub my-ph-ee-g2psandbox-zeebe-gateway-57f6fb9dc5-7d4j6 > zeebe.log


== Docker

== Swagger

https://app.swaggerhub.com/apis/myapi943/payment-hub_ap_is/1.0

== Issue

===  MountVolume.SetUp failed for volume "elastic-certificates" : secret "elastic-certificates" not found


== Official package

helm install my-ph-ee-g2psandbox g2p-sandbox-1-5/ph-ee-g2psandbox --version 1.5.0
helm template my-ph-ee-g2psandbox g2p-sandbox-1-5/ph-ee-g2psandbox --version 1.5.0 --debug > official.yaml

